# Generated by Django 5.1.5 on 2025-03-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
