# Generated by Django 5.1.5 on 2025-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_user_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
