# Generated by Django 5.1.5 on 2025-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(blank=True, default='avatar1.jpeg', null=True),
        ),
    ]
