# Generated by Django 5.1.5 on 2025-05-18 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatarurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrCode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
