# Generated by Django 5.1.5 on 2025-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qrCode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
