# Generated by Django 5.1.5 on 2025-03-13 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='participants',
            field=models.ManyToManyField(related_name='bills', through='bills.BillParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billparticipant',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_participants', to='bills.bill'),
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bills.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_detail',
            field=models.ManyToManyField(related_name='bills', to='bills.billdetail'),
        ),
    ]
