# Generated by Django 5.1.5 on 2025-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_participants_alter_billparticipant_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
