# Generated by Django 5.1.5 on 2025-03-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_add_split_amount_to_billparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetail',
            old_name='item_price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='billdetail',
            old_name='item_name',
            new_name='description',
        ),
    ]
